public enum GameAction {
    MOVE_THROW_DICE,
    TRADE_OFFER,
    TRADE_ACCEPT,
    TRADE_REJECT,
    PROPERTY_BUY_OR_AUCTION,
    PROPERTY_MORTGAGE,
    PROPERTY_UNMORTGAGE,
    AUCTION_BID,
    HOUSE_BUILD,
    HOUSE_SELL,
    JAIL_THROW_DICE,
    JAIL_PAY_BAIL,
    JAIL_USE_CARD,
    END_TURN
}